export const GET_ALL_MOVIES_STARTED = 'GET_ALL_MOVIES_STARTED'
export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS'
export const GET_ALL_MOVIES_FAILED = 'GET_ALL_MOVIES_FAILED'

export const GET_POPULAR_MOVIES_STARTED = 'GET_POPULAR_MOVIES_STARTED'
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS'
export const GET_POPULAR_MOVIES_FAILED = 'GET_POPULAR_MOVIES_FAILED'

export const GET_NEW_MOVIES_STARTED = 'GET_NEW_MOVIES_STARTED'
export const GET_NEW_MOVIES_SUCCESS = 'GET_NEW_MOVIES_SUCCESS'
export const GET_NEW_MOVIES_FAILED = 'GET_NEW_MOVIES_FAILED'

export const SEARCH_MOVIES_STARTED = 'SEARCH_MOVIES_STARTED'
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS'
export const SEARCH_MOVIES_FAILED = 'SEARCH_MOVIES_FAILED'

export const GET_ONE_MOVIE_STARTED = 'GET_ONE_MOVIE_STARTED'
export const GET_ONE_MOVIE_SUCCESS = 'GET_ONE_MOVIE_SUCCESS'
export const GET_ONE_MOVIE_FAILED = 'GET_ONE_MOVIE_FAILED'