export const USER_REGISTER_STARTED = 'USER_REGISTER_STARTED'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'

export const USER_LOGIN_STARTED = 'USER_LOGIN_STARTED'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_ADD_FAVORITE_MOVIE = 'USER_ADD_FAVORITE_MOVIE'
export const USER_ADD_WATCH_LATER_MOVIE = 'USER_ADD_WATCH_LATER_MOVIE'

export const USER_SAVE_TEST_RESULT = 'USER_SAVE_TEST_RESULT'